root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/zendo ./cmd/zendo/main.go"
  entrypoint = "./tmp/zendo"
  delay = 1000
  include_ext = ["go", "sql", "env"]
  exclude_dir = ["testdata","tmp","vendor"]
  exclude_file = [".*_test.go"]
  kill_delay = 500
  log = "tmp/build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true
  color = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true